---
name: Tk-DirSelect
version: 1.12
author:
  - 'Michael Carman <mjcarman@cpan.org>'
abstract: Cross-platform directory selection widget.
license: perl
build_requires:
  Test::More: 0
requires:
  Tk: 0
configure_requires:
  Module::Build: 0.340201
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  Tk::DirSelect:
    file: lib/Tk/DirSelect.pm
    version: 1.12
resources:
  license: http://dev.perl.org/licenses/
